
import type { Metadata } from "next";

import localFont from "next/font/local";
import "./globals.css";
import Navbar from './navbar/page'; // Ensure correct path
import Footer from './footer/page'; // Ensure correct path

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode; // Type children as ReactNode
}) { // Get the current pathname

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
